import { Poppins } from "next/font/google"; // Import Poppins font from Google
import localFont from "next/font/local";
import "./globals.css";

// Import Poppins instead of Outfit
const poppins = Poppins({ subsets: ['latin'], weight: ['400', '500', '600', '700'] });

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Mediplus +",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
